### PR TITLE
Update es.po

### PR DESCRIPTION
**Pull request by Roberalz**

### CODE REVIEW

**Comment by monetaryabyss** [comment]
@tsimonq2 this LGTM. Merge away :) Thanks for the contribution @Roberalz

**Comment by tsimonq2** [comment]
You are amazing, thank you for all the help!

I'll merge this manually in the next few hours.

**Comment by Roberalz** [comment]
i will correct gl and eu in a moment

**Comment by tsimonq2** [comment]
@Roberalz Please create a new PR when you do. Thank you! :)

**Pull request merged**
